### ISSUE TITLE
RMI related information observed in Github repository - yogesh.jadhav

### ISSUE THREAD

**Issue by anushanarapu** [pgyogesh/pgyogesh#1]
Hi Yogesh,
 
This is Anusha from Rakuten Mobile Security Operations Team. 
 
Our Security team reported us for a GitHub data leakage under your username. 
 
We have observed RMI related details found in a GitHub repository “[pgyogesh](https://github.com/pgyogesh)/[logs-analyzer-python](https://github.com/pgyogesh/logs-analyzer-python)” is publicly accessible.
 
Github URL: https://github.com/pgyogesh/logs-analyzer-python/blob/main/sample.log
 
Attached snapshot below for your reference. Hence, we are requesting to take down the repo ASAP.

**Comment by anushanarapu** [comment]
any update in this?

**Comment by pgyogesh** [comment]
Repo is deleted. Thanks
